<?php

declare(strict_types=1);

namespace Modules\GameTables\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\GameTables\Infrastructure\Persistence\Eloquent\Models\GameSystemModel;
use Modules\GameTables\Infrastructure\Persistence\Eloquent\Models\PublisherModel;

final class GameSystemsSeeder extends Seeder
{
    public function run(): void
    {
        // First run publishers seeder to ensure they exist
        $this->call(PublishersSeeder::class);

        // Cache publishers by slug
        $publishers = PublisherModel::query()->pluck('id', 'slug')->toArray();

        $systems = [
            // Sistemas de fantasía
            [
                'name' => 'Dungeons & Dragons 5th Edition',
                'slug' => 'dnd-5e',
                'description' => 'La quinta edición del juego de rol más famoso del mundo.',
                'publisher_slug' => 'wizards-of-the-coast',
                'edition' => '5th Edition',
                'year' => 2014,
                'website_url' => 'https://dnd.wizards.com/',
                'game_master_title' => 'Dungeon Master',
                'is_active' => true,
            ],
            [
                'name' => 'Dungeons & Dragons 2024',
                'slug' => 'dnd-2024',
                'description' => 'La nueva edición revisada de D&D con reglas actualizadas.',
                'publisher_slug' => 'wizards-of-the-coast',
                'edition' => '2024 Revised',
                'year' => 2024,
                'website_url' => 'https://dnd.wizards.com/',
                'game_master_title' => 'Dungeon Master',
                'is_active' => true,
            ],
            [
                'name' => 'Pathfinder 2nd Edition',
                'slug' => 'pathfinder-2e',
                'description' => 'Un juego de rol de fantasía con un sistema de reglas detallado.',
                'publisher_slug' => 'paizo',
                'edition' => '2nd Edition',
                'year' => 2019,
                'website_url' => 'https://paizo.com/pathfinder',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],
            [
                'name' => 'Warhammer Fantasy Roleplay 4th Edition',
                'slug' => 'wfrp-4e',
                'description' => 'Juego de rol de fantasía oscura en el Viejo Mundo.',
                'publisher_slug' => 'cubicle-7',
                'edition' => '4th Edition',
                'year' => 2018,
                'website_url' => 'https://cubicle7games.com/warhammer-fantasy-roleplay',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],
            [
                'name' => 'The One Ring 2nd Edition',
                'slug' => 'one-ring-2e',
                'description' => 'Juego de rol ambientado en la Tierra Media de Tolkien.',
                'publisher_slug' => 'free-league',
                'edition' => '2nd Edition',
                'year' => 2021,
                'website_url' => 'https://freeleaguepublishing.com/games/the-one-ring/',
                'game_master_title' => 'Loremaster',
                'is_active' => true,
            ],
            [
                'name' => 'Forbidden Lands',
                'slug' => 'forbidden-lands',
                'description' => 'Juego de rol de fantasía con exploración y supervivencia.',
                'publisher_slug' => 'free-league',
                'edition' => null,
                'year' => 2018,
                'website_url' => 'https://freeleaguepublishing.com/games/forbidden-lands/',
                'game_master_title' => 'Gamemaster',
                'is_active' => true,
            ],
            [
                'name' => 'Dragonbane',
                'slug' => 'dragonbane',
                'description' => 'Juego de rol de fantasía clásica con reglas modernas.',
                'publisher_slug' => 'free-league',
                'edition' => null,
                'year' => 2023,
                'website_url' => 'https://freeleaguepublishing.com/games/dragonbane/',
                'game_master_title' => 'Gamemaster',
                'is_active' => true,
            ],
            [
                'name' => 'Mork Borg',
                'slug' => 'mork-borg',
                'description' => 'Juego de rol OSR de fantasía oscura y apocalíptica.',
                'publisher_slug' => 'free-league',
                'edition' => null,
                'year' => 2020,
                'website_url' => 'https://morkborg.com/',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],

            // Sistemas de terror
            [
                'name' => 'Call of Cthulhu 7th Edition',
                'slug' => 'call-of-cthulhu-7e',
                'description' => 'Juego de rol de horror cósmico basado en las obras de H.P. Lovecraft.',
                'publisher_slug' => 'chaosium',
                'edition' => '7th Edition',
                'year' => 2014,
                'website_url' => 'https://www.chaosium.com/call-of-cthulhu-rpg/',
                'game_master_title' => 'Keeper',
                'is_active' => true,
            ],
            [
                'name' => 'Vaesen',
                'slug' => 'vaesen',
                'description' => 'Juego de rol de horror nórdico y folclore escandinavo.',
                'publisher_slug' => 'free-league',
                'edition' => null,
                'year' => 2020,
                'website_url' => 'https://freeleaguepublishing.com/games/vaesen/',
                'game_master_title' => 'Gamemaster',
                'is_active' => true,
            ],
            [
                'name' => 'Delta Green',
                'slug' => 'delta-green',
                'description' => 'Juego de rol de horror conspirativo y agencias secretas.',
                'publisher_slug' => 'arc-dream',
                'edition' => null,
                'year' => 2016,
                'website_url' => 'https://www.delta-green.com/',
                'game_master_title' => 'Handler',
                'is_active' => true,
            ],
            [
                'name' => 'La caída de Delta Green',
                'slug' => 'fall-of-delta-green',
                'description' => 'Delta Green en los años 60 usando el sistema GUMSHOE.',
                'publisher_slug' => 'pelgrane',
                'edition' => null,
                'year' => 2018,
                'website_url' => 'https://pelgranepress.com/product/the-fall-of-delta-green/',
                'game_master_title' => 'Handler',
                'is_active' => true,
            ],
            [
                'name' => 'Dread',
                'slug' => 'dread',
                'description' => 'Juego de rol de terror que usa una torre Jenga.',
                'publisher_slug' => 'impossible-dream',
                'edition' => null,
                'year' => 2005,
                'website_url' => null,
                'game_master_title' => 'Host',
                'is_active' => true,
            ],

            // World of Darkness
            [
                'name' => 'Vampire: The Masquerade 5th Edition',
                'slug' => 'vtm-5e',
                'description' => 'Juego de rol de horror personal donde los jugadores son vampiros.',
                'publisher_slug' => 'renegade',
                'edition' => '5th Edition',
                'year' => 2018,
                'website_url' => 'https://worldofdarkness.com/',
                'game_master_title' => 'Storyteller',
                'is_active' => true,
            ],
            [
                'name' => 'Werewolf: The Apocalypse 5th Edition',
                'slug' => 'wta-5e',
                'description' => 'Juego de rol donde los jugadores son licántropos protectores de Gaia.',
                'publisher_slug' => 'renegade',
                'edition' => '5th Edition',
                'year' => 2023,
                'website_url' => 'https://worldofdarkness.com/',
                'game_master_title' => 'Storyteller',
                'is_active' => true,
            ],
            [
                'name' => 'Hunter: The Reckoning 5th Edition',
                'slug' => 'htr-5e',
                'description' => 'Juego de rol donde los jugadores son cazadores de monstruos.',
                'publisher_slug' => 'renegade',
                'edition' => '5th Edition',
                'year' => 2022,
                'website_url' => 'https://worldofdarkness.com/',
                'game_master_title' => 'Storyteller',
                'is_active' => true,
            ],

            // Ciencia ficción
            [
                'name' => 'Mothership',
                'slug' => 'mothership',
                'description' => 'Juego de rol de terror espacial de ciencia ficción.',
                'publisher_slug' => 'tuesday-knight',
                'edition' => '1st Edition',
                'year' => 2018,
                'website_url' => 'https://www.mothershiprpg.com/',
                'game_master_title' => 'Warden',
                'is_active' => true,
            ],
            [
                'name' => 'Alien RPG',
                'slug' => 'alien-rpg',
                'description' => 'Juego de rol oficial del universo de Alien.',
                'publisher_slug' => 'free-league',
                'edition' => null,
                'year' => 2019,
                'website_url' => 'https://freeleaguepublishing.com/games/alien/',
                'game_master_title' => 'Game Mother',
                'is_active' => true,
            ],
            [
                'name' => 'Blade Runner RPG',
                'slug' => 'blade-runner-rpg',
                'description' => 'Juego de rol oficial del universo de Blade Runner.',
                'publisher_slug' => 'free-league',
                'edition' => null,
                'year' => 2022,
                'website_url' => 'https://freeleaguepublishing.com/games/blade-runner/',
                'game_master_title' => 'Game Runner',
                'is_active' => true,
            ],
            [
                'name' => 'Cyberpunk RED',
                'slug' => 'cyberpunk-red',
                'description' => 'Juego de rol cyberpunk en un futuro distópico.',
                'publisher_slug' => 'r-talsorian',
                'edition' => null,
                'year' => 2020,
                'website_url' => 'https://rtalsoriangames.com/cyberpunk/',
                'game_master_title' => 'Referee',
                'is_active' => true,
            ],
            [
                'name' => 'Traveller',
                'slug' => 'traveller',
                'description' => 'Juego de rol de ciencia ficción clásico de exploración espacial.',
                'publisher_slug' => 'mongoose',
                'edition' => '2nd Edition',
                'year' => 2016,
                'website_url' => 'https://www.mongoosepublishing.com/collections/traveller-rpgs',
                'game_master_title' => 'Referee',
                'is_active' => true,
            ],
            [
                'name' => 'Stars Without Number',
                'slug' => 'swn',
                'description' => 'Juego de rol OSR de ciencia ficción con herramientas para sandbox.',
                'publisher_slug' => 'sine-nomine',
                'edition' => 'Revised Edition',
                'year' => 2017,
                'website_url' => null,
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],

            // Narrativos/Indie
            [
                'name' => 'Blades in the Dark',
                'slug' => 'blades-in-the-dark',
                'description' => 'Juego de rol de atracos y bandas criminales en una ciudad oscura.',
                'publisher_slug' => 'evil-hat',
                'edition' => null,
                'year' => 2017,
                'website_url' => 'https://bladesinthedark.com/',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],
            [
                'name' => 'Apocalypse World',
                'slug' => 'apocalypse-world',
                'description' => 'Juego de rol post-apocalíptico que originó los juegos PbtA.',
                'publisher_slug' => 'lumpley',
                'edition' => '2nd Edition',
                'year' => 2016,
                'website_url' => 'http://apocalypse-world.com/',
                'game_master_title' => 'Master of Ceremonies',
                'is_active' => true,
            ],
            [
                'name' => 'Dungeon World',
                'slug' => 'dungeon-world',
                'description' => 'Juego de rol de fantasía usando el motor Powered by the Apocalypse.',
                'publisher_slug' => 'sage-kobold',
                'edition' => null,
                'year' => 2012,
                'website_url' => 'https://dungeon-world.com/',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],
            [
                'name' => 'Monster of the Week',
                'slug' => 'monster-of-the-week',
                'description' => 'Juego PbtA de caza de monstruos al estilo de series como Buffy o Supernatural.',
                'publisher_slug' => 'evil-hat',
                'edition' => null,
                'year' => 2012,
                'website_url' => 'https://www.evilhat.com/home/monster-of-the-week/',
                'game_master_title' => 'Keeper',
                'is_active' => true,
            ],
            [
                'name' => 'FATE Core',
                'slug' => 'fate-core',
                'description' => 'Sistema genérico narrativo basado en aspectos.',
                'publisher_slug' => 'evil-hat',
                'edition' => null,
                'year' => 2013,
                'website_url' => 'https://www.evilhat.com/home/fate-core/',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],
            [
                'name' => 'Fiasco',
                'slug' => 'fiasco',
                'description' => 'Juego de rol de ambición, desastre y planes que salen mal.',
                'publisher_slug' => 'bully-pulpit',
                'edition' => null,
                'year' => 2009,
                'website_url' => 'https://bullypulpitgames.com/games/fiasco/',
                'game_master_title' => 'Facilitador',
                'is_active' => true,
            ],
            [
                'name' => 'Kids on Bikes',
                'slug' => 'kids-on-bikes',
                'description' => 'Juego de rol colaborativo de aventuras de niños al estilo Stranger Things.',
                'publisher_slug' => 'renegade',
                'edition' => null,
                'year' => 2018,
                'website_url' => 'https://renegadegamestudios.com/kids-on-bikes/',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],

            // Sistemas españoles
            [
                'name' => 'Aquelarre',
                'slug' => 'aquelarre',
                'description' => 'Juego de rol de fantasía medieval ibérica.',
                'publisher_slug' => 'nosolorol',
                'edition' => '3rd Edition',
                'year' => 2019,
                'website_url' => 'https://nosolorol.com/aquelarre',
                'game_master_title' => 'Director de juego',
                'is_active' => true,
            ],
            [
                'name' => 'El Resurgir del Dragón',
                'slug' => 'resurgir-dragon',
                'description' => 'Juego de rol de fantasía épica español.',
                'publisher_slug' => 'nosolorol',
                'edition' => null,
                'year' => 2016,
                'website_url' => 'https://nosolorol.com/el-resurgir-del-dragon',
                'game_master_title' => 'Director de juego',
                'is_active' => true,
            ],
            [
                'name' => 'Cultos Innombrables',
                'slug' => 'cultos-innombrables',
                'description' => 'Juego de rol de terror lovecraftiano español.',
                'publisher_slug' => 'nosolorol',
                'edition' => null,
                'year' => 2018,
                'website_url' => 'https://nosolorol.com/cultos-innombrables',
                'game_master_title' => 'Guardián',
                'is_active' => true,
            ],
            [
                'name' => 'Labyrinth Lord',
                'slug' => 'labyrinth-lord',
                'description' => 'Retroclón de D&D básico, popular en España.',
                'publisher_slug' => 'goblinoid',
                'edition' => null,
                'year' => 2007,
                'website_url' => null,
                'game_master_title' => 'Labyrinth Lord',
                'is_active' => true,
            ],

            // Genéricos
            [
                'name' => 'GURPS',
                'slug' => 'gurps',
                'description' => 'Sistema de rol universal genérico.',
                'publisher_slug' => 'steve-jackson',
                'edition' => '4th Edition',
                'year' => 2004,
                'website_url' => 'https://www.sjgames.com/gurps/',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],
            [
                'name' => 'Savage Worlds',
                'slug' => 'savage-worlds',
                'description' => 'Sistema genérico de acción pulp rápido y divertido.',
                'publisher_slug' => 'pinnacle',
                'edition' => 'Adventure Edition',
                'year' => 2019,
                'website_url' => 'https://peginc.com/savage-settings/savage-worlds/',
                'game_master_title' => 'Game Master',
                'is_active' => true,
            ],
            [
                'name' => 'Year Zero Engine',
                'slug' => 'year-zero-engine',
                'description' => 'Motor genérico usado por Free League para varios juegos.',
                'publisher_slug' => 'free-league',
                'edition' => null,
                'year' => 2014,
                'website_url' => 'https://freeleaguepublishing.com/',
                'game_master_title' => 'Gamemaster',
                'is_active' => true,
            ],

            // Otros
            [
                'name' => 'Otro sistema',
                'slug' => 'otro',
                'description' => 'Para sistemas que no están en la lista.',
                'publisher_slug' => null,
                'edition' => null,
                'year' => null,
                'website_url' => null,
                'game_master_title' => 'Director de juego',
                'is_active' => true,
            ],
        ];

        foreach ($systems as $system) {
            $publisherSlug = $system['publisher_slug'] ?? null;
            unset($system['publisher_slug']);

            $system['publisher_id'] = $publisherSlug ? ($publishers[$publisherSlug] ?? null) : null;

            GameSystemModel::query()->updateOrCreate(
                ['slug' => $system['slug']],
                $system,
            );
        }
    }
}
